// ============================================================================
//  L2_005ad2e0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x005ad2e0  FUN_005ad2e0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 58 B. Plate:
// hooks.csv row 0x005ad2e0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
static inline unsigned int L2T_FUN_004522d0(unsigned int a0) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int)>(0x004522d0u)(a0); }   // 0x004522d0 (original, not ported)
extern "C" unsigned int __cdecl L2_FUN_005ad2e0(int param_1);
static unsigned int __cdecl L2_FUN_005ad2e0_impl(int param_1)
{
  if (*(int *)(param_1 + 0xc) != 0) {
    *(int *)(param_1 + 0xc) = *(int *)(param_1 + 0xc) + -1;
    return 0;
  }
  **(undefined4 **)(param_1 + 0x18) = *(undefined4 *)(param_1 + 0x14);
  *(undefined4 *)(*(int *)(param_1 + 0x14) + 4) = *(undefined4 *)(param_1 + 0x18);
  if ((*(byte *)(param_1 + 0x10) & 1) == 0) {
    L2T_FUN_004522d0((unsigned int)(param_1));
  }
  return 1;
}
extern "C" unsigned int __cdecl L2_FUN_005ad2e0(int param_1) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_005ad2e0", 0x005ad2e0u, ShadowAB::kPhaseRace);
    return ShadowAB::Run(ab, L2_FUN_005ad2e0_impl, param_1);
}
RH_ScopedInstall(L2_FUN_005ad2e0, 0x005ad2e0);
