// ============================================================================
//  L2_0041f290.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x0041f290  FUN_0041f290  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 36 B. Plate:
// hooks.csv row 0x0041f290. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_0063d9e0 (*(unsigned char*)0x0063d9e0u)   // .data, undefined
static inline int L2T_FUN_004c0ed0(int a0) { return reinterpret_cast<int(__cdecl*)(int)>(0x004c0ed0u)(a0); }   // 0x004c0ed0 (original, not ported)
extern "C" void __cdecl L2_FUN_0041f290(int param_1, int param_2);
static void __cdecl L2_FUN_0041f290_impl(int param_1, int param_2)
{
  L2T_FUN_004c0ed0((int)(*(undefined4 *)(*(int *)(&DAT_0063d9e0 + (param_1 * 0xab + param_2) * 4) + 4)));
  return;
}
extern "C" void __cdecl L2_FUN_0041f290(int param_1, int param_2) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_0041f290", 0x0041f290u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_0041f290_impl, SHADOW_STACK_WINDOW(), param_1, param_2);
}
RH_ScopedInstall(L2_FUN_0041f290, 0x0041f290);
#undef DAT_0063d9e0
