// ============================================================================
//  L2_00489890.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00489890  FUN_00489890  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 55 B. Plate:
// hooks.csv row 0x00489890. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define _DAT_00703110 (*(unsigned char*)0x00703110u)   // .data, undefined
static inline void L2T_FUN_00476df0(int a0) { reinterpret_cast<void(__cdecl*)(int)>(0x00476df0u)(a0); }   // 0x00476df0 (original, not ported)
static inline void L2T_FUN_00489500(int * a0) { reinterpret_cast<void(__cdecl*)(int *)>(0x00489500u)(a0); }   // 0x00489500 (original, not ported)
extern "C" void __cdecl L2_FUN_00489890(int param_1);
static void __cdecl L2_FUN_00489890_impl(int param_1)
{
  if (*(int *)(param_1 + 0x54) != 0) {
    L2T_FUN_00489500((int *)(param_1));
    L2T_FUN_00476df0((int)(param_1 + 0x10));
    _DAT_00703110 = *(undefined4 *)(param_1 + 8);
    *(undefined4 *)(param_1 + 8) = 0;
    *(undefined4 *)(param_1 + 0xc) = 1;
  }
  return;
}
extern "C" void __cdecl L2_FUN_00489890(int param_1) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_00489890", 0x00489890u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_00489890_impl, SHADOW_STACK_WINDOW(), param_1);
}
RH_ScopedInstall(L2_FUN_00489890, 0x00489890);
#undef _DAT_00703110
