// ============================================================================
//  L2_00475ef0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00475ef0  FUN_00475ef0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 49 B. Plate:
// hooks.csv row 0x00475ef0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_00613254 (*(unsigned int*)0x00613254u)   // .data, undefined4
#define DAT_00691698 (*(unsigned char*)0x00691698u)   // .data, undefined
extern "C" void __cdecl ZeroFillWrapper(unsigned int, unsigned int);   // 0x004b6520 (ported)
extern "C" void __cdecl L2_FUN_00475ef0(void);
extern "C" void __cdecl L2_FUN_00475ef0(void)
{
  undefined *puVar1;
  
  puVar1 = &DAT_00691698;
  do {
    ZeroFillWrapper((unsigned int)(puVar1), (unsigned int)(0xd8));
    *(undefined4 *)(puVar1 + 0xc0) = DAT_00613254;
    puVar1 = puVar1 + 0xd8;
  } while ((int)puVar1 < 0x692418);
  return;
}
RH_ScopedInstall(L2_FUN_00475ef0, 0x00475ef0);
#undef DAT_00613254
#undef DAT_00691698
