// ============================================================================
//  L2_00494a80.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00494a80  FUN_00494a80  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 55 B. Plate:
// hooks.csv row 0x00494a80. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_00771a04 (*(unsigned int*)0x00771a04u)   // .data, undefined4
#define DAT_00771a08 (*(unsigned int*)0x00771a08u)   // .data, undefined4
#define DAT_00771a18 (*(unsigned int*)0x00771a18u)   // .data, undefined4
static inline unsigned int L2T_FUN_004944c0(unsigned int a0) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int)>(0x004944c0u)(a0); }   // 0x004944c0 (original, not ported)
static inline int L2T_FUN_004c77c0(unsigned int a0, unsigned int a1, unsigned int a2, unsigned int a3) { return reinterpret_cast<int(__cdecl*)(unsigned int, unsigned int, unsigned int, unsigned int)>(0x004c77c0u)(a0, a1, a2, a3); }   // 0x004c77c0 (original, not ported)
extern "C" void __cdecl L2_FUN_00494a80(unsigned int param_1, unsigned int param_2, unsigned int param_3);
static void __cdecl L2_FUN_00494a80_impl(unsigned int param_1, unsigned int param_2, unsigned int param_3)
{
  DAT_00771a18 = L2T_FUN_004c77c0((unsigned int)(0), (unsigned int)(0), (unsigned int)(0), (unsigned int)(0x84));
  L2T_FUN_004944c0((unsigned int)(param_2));
  DAT_00771a04 = 1;
  DAT_00771a08 = param_3;
  return;
}
extern "C" void __cdecl L2_FUN_00494a80(unsigned int param_1, unsigned int param_2, unsigned int param_3) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_00494a80", 0x00494a80u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_00494a80_impl, SHADOW_STACK_WINDOW(), param_1, param_2, param_3);
}
RH_ScopedInstall(L2_FUN_00494a80, 0x00494a80);
#undef DAT_00771a04
#undef DAT_00771a08
#undef DAT_00771a18
