// ============================================================================
//  L2_00485070.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00485070  FUN_00485070  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 52 B. Plate:
// hooks.csv row 0x00485070. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_006e70c8 (*(int*)0x006e70c8u)   // .data, int
#define DAT_006e70cc (*(unsigned int*)0x006e70ccu)   // .data, undefined4
#define DAT_006e70d4 (*(unsigned int*)0x006e70d4u)   // .data, undefined4
#define DAT_006e70d8 (*(unsigned int*)0x006e70d8u)   // .data, undefined4
static inline void L2T_FUN_00484de0(void) { reinterpret_cast<void(__cdecl*)()>(0x00484de0u)(); }   // 0x00484de0 (original, not ported)
static inline void L2T_FUN_00484f70(void) { reinterpret_cast<void(__cdecl*)()>(0x00484f70u)(); }   // 0x00484f70 (original, not ported)
extern "C" void __cdecl L2_FUN_00485070(void);
extern "C" void __cdecl L2_FUN_00485070(void)
{
  if (DAT_006e70c8 == 0) {
    L2T_FUN_00484f70();
  }
  else {
    L2T_FUN_00484de0();
  }
  DAT_006e70d8 = DAT_006e70cc;
  DAT_006e70cc = 0;
  DAT_006e70d4 = 0;
  return;
}
RH_ScopedInstall(L2_FUN_00485070, 0x00485070);
#undef DAT_006e70c8
#undef DAT_006e70cc
#undef DAT_006e70d4
#undef DAT_006e70d8
