// ============================================================================
//  L2_005af010.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x005af010  FUN_005af010  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 46 B. Plate:
// hooks.csv row 0x005af010. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
static inline void L2T_FUN_005af2d0(unsigned int a0, unsigned int a1, unsigned int * a2) { reinterpret_cast<void(__cdecl*)(unsigned int, unsigned int, unsigned int *)>(0x005af2d0u)(a0, a1, a2); }   // 0x005af2d0 (original, not ported)
static inline unsigned int L2T_FUN_005af510(int a0, unsigned int a1, unsigned int * a2) { return reinterpret_cast<unsigned int(__cdecl*)(int, unsigned int, unsigned int *)>(0x005af510u)(a0, a1, a2); }   // 0x005af510 (original, not ported)
extern "C" unsigned int __cdecl L2_FUN_005af010(int param_1);
static unsigned int __cdecl L2_FUN_005af010_impl(int param_1)
{
  undefined4 uVar1;
  
  uVar1 = L2T_FUN_005af510((int)(param_1), (unsigned int)(param_1 + 0x5c), (unsigned int *)(param_1 + 0x68));
  L2T_FUN_005af2d0((unsigned int)(param_1), (unsigned int)(param_1 + 0x5c), (unsigned int *)(param_1 + 0xc80));
  return uVar1;
}
extern "C" unsigned int __cdecl L2_FUN_005af010(int param_1) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_005af010", 0x005af010u, ShadowAB::kPhaseRace);
    return ShadowAB::Run(ab, L2_FUN_005af010_impl, param_1);
}
RH_ScopedInstall(L2_FUN_005af010, 0x005af010);
