// ============================================================================
//  L2_0045cc50.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x0045cc50  FUN_0045cc50  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 47 B. Plate:
// hooks.csv row 0x0045cc50. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
extern "C" unsigned int __cdecl GetRenderSubMode(void);   // 0x0040e350 (ported)
static inline unsigned int L2T_FUN_0045cbe0(unsigned int a0, unsigned int a1, unsigned int a2) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int, unsigned int, unsigned int)>(0x0045cbe0u)(a0, a1, a2); }   // 0x0045cbe0 (original, not ported)
extern "C" void __cdecl L2_FUN_0045cc50(void);
static void __cdecl L2_FUN_0045cc50_impl(void)
{
  int iVar1;
  
  iVar1 = GetRenderSubMode();
  if (iVar1 == 2) {
    iVar1 = 0;
    do {
      L2T_FUN_0045cbe0((unsigned int)(1), (unsigned int)(iVar1), (unsigned int)(0xffffffff));
      L2T_FUN_0045cbe0((unsigned int)(0), (unsigned int)(iVar1), (unsigned int)(0xffffffff));
      iVar1 = iVar1 + 1;
    } while (iVar1 < 4);
  }
  return;
}
extern "C" void __cdecl L2_FUN_0045cc50(void) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_0045cc50", 0x0045cc50u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_0045cc50_impl, SHADOW_STACK_WINDOW());
}
RH_ScopedInstall(L2_FUN_0045cc50, 0x0045cc50);
