// ============================================================================
//  L2_00426030.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00426030  FUN_00426030  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 47 B. Plate:
// hooks.csv row 0x00426030. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_00644158 (*(unsigned int*)0x00644158u)   // .data, undefined4
#define DAT_00646e58 (*(unsigned char*)0x00646e58u)   // .data, undefined
#define _DAT_005f616c (*(unsigned char*)0x005f616cu)   // .data, undefined
static inline unsigned int L2T_FUN_0041e8f0(unsigned int a0) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int)>(0x0041e8f0u)(a0); }   // 0x0041e8f0 (original, not ported)
extern "C" bool __cdecl TrackNodeFieldCmp10(int);   // 0x0041e9b0 (ported)
static inline unsigned int L2T_FUN_0041ea10(void) { return reinterpret_cast<unsigned int(__cdecl*)()>(0x0041ea10u)(); }   // 0x0041ea10 (original, not ported)
extern "C" void __cdecl L2_FUN_00426030(void);
extern "C" void __cdecl L2_FUN_00426030(void)
{
  int iVar1;
  
  TrackNodeFieldCmp10((int)(DAT_00644158));
  iVar1 = L2T_FUN_0041ea10();
  if (iVar1 != 0) {
    L2T_FUN_0041e8f0((unsigned int)(&DAT_00646e58));
    _DAT_005f616c = 1;
  }
  return;
}
RH_ScopedInstall(L2_FUN_00426030, 0x00426030);
#undef DAT_00644158
#undef DAT_00646e58
#undef _DAT_005f616c
