// ============================================================================
//  L2_005ab1c0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x005ab1c0  FUN_005ab1c0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 56 B. Plate:
// hooks.csv row 0x005ab1c0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
static inline unsigned int L2T_FUN_005509b0(int a0, unsigned int a1, int a2) { return reinterpret_cast<unsigned int(__cdecl*)(int, unsigned int, int)>(0x005509b0u)(a0, a1, a2); }   // 0x005509b0 (original, not ported)
extern "C" void __cdecl L2_FUN_005ab1c0(int * param_1, unsigned int param_2, int param_3, int param_4);
extern "C" void __cdecl L2_FUN_005ab1c0(int * param_1, unsigned int param_2, int param_3, int param_4)
{
  param_1[0x11] = param_3;
  param_1[4] = param_2;
  param_1[0x12] = param_4;
  param_1[0x10] = 3;
  L2T_FUN_005509b0((int)(*(undefined4 *)(*param_1 + 0xc)), (unsigned int)(param_2 & 0xfffff800), (int)(0));
  return;
}
RH_ScopedInstall(L2_FUN_005ab1c0, 0x005ab1c0);
