// ============================================================================
//  L2_0048fd40.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x0048fd40  FUN_0048fd40  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 39 B. Plate:
// hooks.csv row 0x0048fd40. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_007669b8 (*(unsigned char*)0x007669b8u)   // .data, undefined
// idiom: (*(DAT_007d3ff8+0x20))(...) is __cdecl per MenuDrawLoopTwin.cpp vt20 / RwIm2DBridge.cpp
static inline unsigned int L2_slot_007d3ff8_0x20_2(unsigned int a0, unsigned int a1) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int, unsigned int)>(*reinterpret_cast<unsigned int*>(*reinterpret_cast<unsigned int*>(0x007d3ff8u) + 0x20))(a0, a1); }
static inline void L2T_FUN_004770a0(int a0) { reinterpret_cast<void(__cdecl*)(int)>(0x004770a0u)(a0); }   // 0x004770a0 (original, not ported)
extern "C" void __cdecl L2_FUN_0048fd40(void);
static void __cdecl L2_FUN_0048fd40_impl(void)
{
  L2_slot_007d3ff8_0x20_2((unsigned int)(8), (unsigned int)(0));
  L2T_FUN_004770a0((int)(&DAT_007669b8));
  L2_slot_007d3ff8_0x20_2((unsigned int)(8), (unsigned int)(1));
  return;
}
extern "C" void __cdecl L2_FUN_0048fd40(void) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_0048fd40", 0x0048fd40u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_0048fd40_impl, SHADOW_STACK_WINDOW());
}
RH_ScopedInstall(L2_FUN_0048fd40, 0x0048fd40);
#undef DAT_007669b8
