// ============================================================================
//  L2_005aeed0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x005aeed0  FUN_005aeed0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 33 B. Plate:
// hooks.csv row 0x005aeed0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
extern "C" bool __cdecl L2_FUN_005aeed0(unsigned int * param_1);
static bool __cdecl L2_FUN_005aeed0_impl(unsigned int * param_1)
{
  DWORD DVar1;
  
  DVar1 = WaitForSingleObject((HANDLE)*param_1,0);
  return DVar1 != 0x102;
}
extern "C" bool __cdecl L2_FUN_005aeed0(unsigned int * param_1) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_005aeed0", 0x005aeed0u, ShadowAB::kPhaseRace);
    return ShadowAB::Run(ab, L2_FUN_005aeed0_impl, param_1);
}
RH_ScopedInstall(L2_FUN_005aeed0, 0x005aeed0);
