// ============================================================================
//  L2_0045dfc0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x0045dfc0  FUN_0045dfc0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 46 B. Plate:
// hooks.csv row 0x0045dfc0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_006036cc (*(float*)0x006036ccu)   // .data, float
#define _DAT_005cc320 (*(const unsigned int*)0x005cc320u)   // .rdata, undefined4
extern "C" void __cdecl FloatStep45df70(float);   // 0x0045df70 (ported)
extern "C" void __cdecl L2_FUN_0045dfc0(void);
static void __cdecl L2_FUN_0045dfc0_impl(void)
{
  if (DAT_006036cc < _DAT_005cc320) {
    FloatStep45df70((float)(DAT_006036cc));
    return;
  }
  FloatStep45df70(f32bits(0x3f800000u));
  return;
}
extern "C" void __cdecl L2_FUN_0045dfc0(void) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_0045dfc0", 0x0045dfc0u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_0045dfc0_impl, SHADOW_STACK_WINDOW());
}
RH_ScopedInstall(L2_FUN_0045dfc0, 0x0045dfc0);
#undef DAT_006036cc
#undef _DAT_005cc320
