// ============================================================================
//  L2_004219c0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x004219c0  FUN_004219c0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 42 B. Plate:
// hooks.csv row 0x004219c0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_0063fb90 (*(unsigned char*)0x0063fb90u)   // .data, undefined
#define DAT_006403b0 (*(unsigned int*)0x006403b0u)   // .data, undefined4
#define DAT_007d3ff8 (*(unsigned int **)0x007d3ff8u)   // .data, undefined4 *
static inline void L2T_FUN_00421720(void) { reinterpret_cast<void(__cdecl*)()>(0x00421720u)(); }   // 0x00421720 (original, not ported)
extern "C" void __cdecl L2_FUN_004219c0(void);
extern "C" void __cdecl L2_FUN_004219c0(void)
{
  undefined *puVar1;
  
  DAT_006403b0 = *DAT_007d3ff8;
  puVar1 = &DAT_0063fb90;
  do {
    L2T_FUN_00421720();
    puVar1 = puVar1 + 0x208;
  } while ((int)puVar1 < 0x6403b0);
  return;
}
RH_ScopedInstall(L2_FUN_004219c0, 0x004219c0);
#undef DAT_0063fb90
#undef DAT_006403b0
#undef DAT_007d3ff8
