// ============================================================================
//  L2_00490490.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00490490  FUN_00490490  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 52 B. Plate:
// hooks.csv row 0x00490490. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_0086a4a4 (*(unsigned int*)0x0086a4a4u)   // .data, undefined4
// idiom: (*(DAT_007d3ff8+0x20))(...) is __cdecl per MenuDrawLoopTwin.cpp vt20 / RwIm2DBridge.cpp
static inline unsigned int L2_slot_007d3ff8_0x20_2(unsigned int a0, unsigned int a1) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int, unsigned int)>(*reinterpret_cast<unsigned int*>(*reinterpret_cast<unsigned int*>(0x007d3ff8u) + 0x20))(a0, a1); }
static inline int L2T_FUN_004e6680(int a0) { return reinterpret_cast<int(__cdecl*)(int)>(0x004e6680u)(a0); }   // 0x004e6680 (original, not ported)
extern "C" void __cdecl L2_FUN_00490490(void);
static void __cdecl L2_FUN_00490490_impl(void)
{
  undefined4 *puVar1;
  
  L2_slot_007d3ff8_0x20_2((unsigned int)(0x14), (unsigned int)(1));
  puVar1 = &DAT_0086a4a4;
  do {
    if (puVar1[-1] != 0) {
      L2T_FUN_004e6680((int)(*puVar1));
    }
    puVar1 = puVar1 + 0x14;
  } while ((int)puVar1 < 0x86ae04);
  return;
}
extern "C" void __cdecl L2_FUN_00490490(void) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_00490490", 0x00490490u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_00490490_impl, SHADOW_STACK_WINDOW());
}
RH_ScopedInstall(L2_FUN_00490490, 0x00490490);
#undef DAT_0086a4a4
