// ============================================================================
//  L2_00442a20.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00442a20  FUN_00442a20  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 51 B. Plate:
// hooks.csv row 0x00442a20. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_0089650c (*(unsigned int*)0x0089650cu)   // .data, undefined4
#define DAT_00896580 (*(unsigned int*)0x00896580u)   // .data, undefined4
static inline void L2T_FUN_00441700(int a0) { reinterpret_cast<void(__cdecl*)(int)>(0x00441700u)(a0); }   // 0x00441700 (original, not ported)
extern "C" void __cdecl L2_FUN_00442a20(int param_1);
static void __cdecl L2_FUN_00442a20_impl(int param_1)
{
  int iVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  
  *(undefined4 *)(param_1 + 0x58) = DAT_00896580;
  L2T_FUN_00441700((int)(param_1));
  puVar2 = &DAT_0089650c;
  puVar3 = (undefined4 *)(*(int *)(*(int *)(param_1 + 0x84) + 4) + 0x10);
  for (iVar1 = 0x10; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar3 = *puVar2;
    puVar2 = puVar2 + 1;
    puVar3 = puVar3 + 1;
  }
  return;
}
extern "C" void __cdecl L2_FUN_00442a20(int param_1) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_00442a20", 0x00442a20u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_00442a20_impl, SHADOW_STACK_WINDOW(), param_1);
}
RH_ScopedInstall(L2_FUN_00442a20, 0x00442a20);
#undef DAT_0089650c
#undef DAT_00896580
