// ============================================================================
//  EXCLUDED FROM THE BUILD 2026-09-10 -- removed from mashedmod/asi_sources.rsp.
//  KEPT ON DISK AS EVIDENCE, NOT AS CODE. Do not re-add without regenerating.
//
//  This port should never have been generated. HIDDEN REGISTER ARGUMENT: the body
//  is `puVar1 = &DAT_0063fb90; do { FUN_00421720(); puVar1 += 0x208; } while
//  ((int)puVar1 < 0x6403b0)` -- a pointer advanced 0x208 per iteration and never
//  passed to a zero-argument call, which means FUN_00421720 reads it from a
//  register Ghidra did not model. Calling it through a cdecl thunk leaves that
//  register undefined. It CRASHES on both A/B arms (armed and --no-shadow).
//
//  decomp2port.py's HIDDEN_REG_ARG refusal was written FROM THIS RVA -- its
//  comment cites this address and this 0x208 stride -- but 13 stray control bytes
//  had replaced `\b` with 0x08 and `\1` with 0x01 in its regexes, so the refusal
//  could never fire and this TU generated anyway. The bytes are repaired and the
//  refusal now rejects this body (re/tools/tests/test_decomp2port_refusals.py).
//  Regenerating will therefore correctly produce nothing.
//
//  Full write-up: re/analysis/decomp2port_refusal_was_disabled_20260910.md
//  Site status:   re/parity/shadow_sites.tsv -> SKIP:hidden-reg-arg
// ============================================================================
// ============================================================================
//  L2_004219c0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x004219c0  FUN_004219c0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 42 B. Plate:
// hooks.csv row 0x004219c0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_0063fb90 (*(unsigned char*)0x0063fb90u)   // .data, undefined
#define DAT_006403b0 (*(unsigned int*)0x006403b0u)   // .data, undefined4
#define DAT_007d3ff8 (*(unsigned int **)0x007d3ff8u)   // .data, undefined4 *
static inline void L2T_FUN_00421720(void) { reinterpret_cast<void(__cdecl*)()>(0x00421720u)(); }   // 0x00421720 (original, not ported)
extern "C" void __cdecl L2_FUN_004219c0(void);
static void __cdecl L2_FUN_004219c0_impl(void)
{
  undefined *puVar1;
  
  DAT_006403b0 = *DAT_007d3ff8;
  puVar1 = &DAT_0063fb90;
  do {
    L2T_FUN_00421720();
    puVar1 = puVar1 + 0x208;
  } while ((int)puVar1 < 0x6403b0);
  return;
}
extern "C" void __cdecl L2_FUN_004219c0(void) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_004219c0", 0x004219c0u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_004219c0_impl, SHADOW_STACK_WINDOW());
}
RH_ScopedInstall(L2_FUN_004219c0, 0x004219c0);
#undef DAT_0063fb90
#undef DAT_006403b0
#undef DAT_007d3ff8
