// ============================================================================
//  L2_0045d3f0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x0045d3f0  FUN_0045d3f0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 53 B. Plate:
// hooks.csv row 0x0045d3f0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_006904e8 (*(int*)0x006904e8u)   // .data, int
#define DAT_006904ec (*(int*)0x006904ecu)   // .data, int
static inline void L2T_FUN_00550be0(void) { reinterpret_cast<void(__cdecl*)()>(0x00550be0u)(); }   // 0x00550be0 (original, not ported)
static inline void L2T_FUN_005a60b0(void) { reinterpret_cast<void(__cdecl*)()>(0x005a60b0u)(); }   // 0x005a60b0 (original, not ported)
extern "C" unsigned int __cdecl L2_FUN_0045d3f0(int param_1);
static unsigned int __cdecl L2_FUN_0045d3f0_impl(int param_1)
{
  if ((DAT_006904e8 != 0) && (DAT_006904ec == 0)) {
    if (param_1 == 0) {
      L2T_FUN_00550be0();
    }
    L2T_FUN_005a60b0();
    DAT_006904ec = 1;
    return 1;
  }
  return 1;
}
extern "C" unsigned int __cdecl L2_FUN_0045d3f0(int param_1) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_0045d3f0", 0x0045d3f0u, ShadowAB::kPhaseRace);
    return ShadowAB::RunTracked(ab, L2_FUN_0045d3f0_impl, SHADOW_STACK_WINDOW(), param_1);
}
RH_ScopedInstall(L2_FUN_0045d3f0, 0x0045d3f0);
#undef DAT_006904e8
#undef DAT_006904ec
