// ============================================================================
//  L2_00495fe0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00495fe0  FUN_00495fe0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 42 B. Plate:
// hooks.csv row 0x00495fe0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_00772fac (*(int*)0x00772facu)   // .data, int
static inline void L2T_FUN_00495870(void) { reinterpret_cast<void(__cdecl*)()>(0x00495870u)(); }   // 0x00495870 (original, not ported)
extern "C" void __cdecl L2_FUN_00495fe0(void);
extern "C" void __cdecl L2_FUN_00495fe0(void)
{
  int iVar1;
  
  iVar1 = 0;
  if (0 < DAT_00772fac) {
    do {
      L2T_FUN_00495870();
      iVar1 = iVar1 + 1;
    } while (iVar1 < DAT_00772fac);
  }
  return;
}
RH_ScopedInstall(L2_FUN_00495fe0, 0x00495fe0);
#undef DAT_00772fac
