// ============================================================================
//  L2_0048f740.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include "../Core/ShadowTrack.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x0048f740  FUN_0048f740  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 39 B. Plate:
// hooks.csv row 0x0048f740. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_00766f40 (*(unsigned int*)0x00766f40u)   // .data, undefined4
extern "C" void __cdecl StridedClear766a00(void);   // 0x0048f6b0 (ported)
extern "C" void __cdecl StridedClear770718(void);   // 0x0048f6e0 (ported)
extern "C" void __cdecl StridedClear769f50(void);   // 0x0048f710 (ported)
extern "C" void __cdecl L2_FUN_0048f740(void);
static void __cdecl L2_FUN_0048f740_impl(void)
{
  undefined4 *puVar1;
  
  StridedClear769f50();
  StridedClear766a00();
  StridedClear770718();
  puVar1 = &DAT_00766f40;
  do {
    *puVar1 = 0;
    puVar1 = puVar1 + 0xc;
  } while ((int)puVar1 < 0x769f40);
  return;
}
extern "C" void __cdecl L2_FUN_0048f740(void) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_0048f740", 0x0048f740u, ShadowAB::kPhaseRace);
    ShadowAB::RunTracked(ab, L2_FUN_0048f740_impl, SHADOW_STACK_WINDOW());
}
RH_ScopedInstall(L2_FUN_0048f740, 0x0048f740);
#undef DAT_00766f40
