// ============================================================================
//  L2_005aa7a0.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x005aa7a0  FUN_005aa7a0  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 60 B. Plate:
// hooks.csv row 0x005aa7a0. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
static inline unsigned int L2T_FUN_005a9e60(unsigned int a0, unsigned int a1, int a2) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int, unsigned int, int)>(0x005a9e60u)(a0, a1, a2); }   // 0x005a9e60 (original, not ported)
static inline void L2T_FUN_005a9f10(int a0, unsigned int a1) { reinterpret_cast<void(__cdecl*)(int, unsigned int)>(0x005a9f10u)(a0, a1); }   // 0x005a9f10 (original, not ported)
extern "C" void __cdecl L2_FUN_005aa7a0(int param_1, unsigned int * param_2, unsigned int param_3, unsigned int param_4);
extern "C" void __cdecl L2_FUN_005aa7a0(int param_1, unsigned int * param_2, unsigned int param_3, unsigned int param_4)
{
  int iVar1;
  
  if (*(int *)(param_1 + 0x48) == 0) {
    iVar1 = L2T_FUN_005a9e60((unsigned int)(param_1), (unsigned int)(param_4), (int)(*param_2 >> 2 & 1));
    if (iVar1 == 0) {
      return;
    }
  }
  L2T_FUN_005a9f10((int)(param_1), (unsigned int)(param_4));
  return;
}
RH_ScopedInstall(L2_FUN_005aa7a0, 0x005aa7a0);
