// ============================================================================
//  L2_005a6e10.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x005a6e10  FUN_005a6e10  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 50 B. Plate:
// hooks.csv row 0x005a6e10. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
static inline unsigned int L2T_FUN_005a6d90(unsigned int * a0, int a1, unsigned int a2, unsigned int a3) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int *, int, unsigned int, unsigned int)>(0x005a6d90u)(a0, a1, a2, a3); }   // 0x005a6d90 (original, not ported)
extern "C" unsigned int __cdecl L2_FUN_005a6e10(unsigned int param_1, unsigned int param_2, unsigned int param_3, unsigned int * param_4);
static unsigned int __cdecl L2_FUN_005a6e10_impl(unsigned int param_1, unsigned int param_2, unsigned int param_3, unsigned int * param_4)
{
  int iVar1;
  
  iVar1 = L2T_FUN_005a6d90((unsigned int *)(param_1), (int)(param_2), (unsigned int)(param_3), (unsigned int)(&param_3));
  if (param_4 != (uint *)0x0) {
    *param_4 = (uint)(iVar1 != 0);
  }
  return param_3;
}
extern "C" unsigned int __cdecl L2_FUN_005a6e10(unsigned int param_1, unsigned int param_2, unsigned int param_3, unsigned int * param_4) {
    SHADOW_AB_COUNTER(ab, "L2_FUN_005a6e10", 0x005a6e10u, ShadowAB::kPhaseRace);
    return ShadowAB::Run(ab, L2_FUN_005a6e10_impl, param_1, param_2, param_3, param_4);
}
RH_ScopedInstall(L2_FUN_005a6e10, 0x005a6e10);
