// ============================================================================
//  L2_00421980.cpp -- Lane 2 GENERATED verbatim ports (re/tools/decomp2port.py, 2026-09-10)
//  Every function below is a mechanical transcription of Ghidra's decompilation of
//  MASHED.exe (anchor in CLAUDE.md). Nothing here is understood or verified by
//  generation: a row moves to C3 only through the shadow A/B (return-value functions
//  carry a ShadowAB::Run wrapper) plus the caller/callee gate in re-classify.
//  Globals are read through their absolute addresses (.asi target only; NOT in
//  exe_sources.rsp). Unported callees are raw-RVA thunks.
// ============================================================================
#include "../Core/HookSystem.h"
#include "../Core/ShadowAB.h"
#include <cstdint>
#include <cstring>

namespace {
inline float f32bits(unsigned int u) { float f; std::memcpy(&f, &u, 4); return f; }
}
typedef unsigned char  undefined;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned int   undefined4;
typedef unsigned char  byte;
typedef unsigned int   uint;
typedef unsigned short ushort;
typedef long double    float10;
typedef void           code;

// ---------------------------------------------------------------------------
// 0x00421980  FUN_00421980  -- GENERATED by re/tools/decomp2port.py from the Ghidra
// decompilation (verbatim; no semantic edits). Size 26 B. Plate:
// hooks.csv row 0x00421980. C-level unchanged by generation; see file header.
// ---------------------------------------------------------------------------
#define DAT_006ce274 (*(unsigned int*)0x006ce274u)   // .data, undefined4
static inline unsigned int L2T_FUN_00559ee0(unsigned int a0) { return reinterpret_cast<unsigned int(__cdecl*)(unsigned int)>(0x00559ee0u)(a0); }   // 0x00559ee0 (original, not ported)
extern "C" unsigned int __cdecl UtilDeref55dec0(unsigned int *);   // 0x0055dec0 (ported)
extern "C" void __cdecl L2_FUN_00421980(void);
extern "C" void __cdecl L2_FUN_00421980(void)
{
  undefined4 uVar1;
  
  uVar1 = UtilDeref55dec0((unsigned int *)(DAT_006ce274));
  L2T_FUN_00559ee0((unsigned int)(uVar1));
  return;
}
RH_ScopedInstall(L2_FUN_00421980, 0x00421980);
#undef DAT_006ce274
